name: Docker Build & Push to GCP

on:
  push:
    branches:
      - main  # Exécuter le workflow quand on push sur `main`

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Se connecter à GCP avec un service account JSON
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Se connecter à Google Artifact Registry
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      # 4️⃣ Construire et pousser l'image
      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/quelpoke/quelpoke-app:latest .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/quelpoke/quelpoke-app:latest
